FROM maven

WORKDIR /app

COPY ./processor/pom.xml ./

COPY ./processor/src ./src
# COPY tests ./tests
COPY conf ./conf

RUN mvn install
RUN touch log-half-second.txt
CMD ["java", "-jar", "target/Processor.jar"]
